### PR TITLE
Deleted unnecessary functions.

### PR DESCRIPTION
**Pull request by 18001767679**

### CODE REVIEW

**Comment by Sombrero64** [comment]
What does the **combine()** function actually do? I am confused.

**Comment by samthatwoz** [comment]
I think the user means that either that Python or an official python library has that function already.

**Comment by 18001767679** [comment]
The combine function I just made yesterday is just like the combine function in snap.

---Original---

**Comment by 18001767679** [comment]
you can use the combine high order function to combine a list using another first class procedure(grey ring)



---Original---

**Comment by 18001767679** [comment]
You see there are four high order functions that operate lists:The map function which python already has;The combined function I made yesterday;The index function(Python already had too so I deleted it as an unnecessary function);And the keep items function that you made。
Do you only use python(not use snap)？

---Original---

**Comment by 18001767679** [comment]
No，They combine function is just in snap so I want to implement it in python.Do you use snap？



---Original---

**Comment by 18001767679** [comment]
That's the unnecessary functions.



---Original---

**Comment by samthatwoz** [comment]
Yeah, he does. I guess he's trying to implement the stuff you can do in Snap.

**Comment by Sombrero64** [comment]
Ah I see. I think that it's not necessary for now, but thank you for your time. And yes, I do use Snap as the bias [sombrero](https://forum.snap.berkeley.edu/u/sombrero/activity).

**Comment by 18001767679** [comment]
Actually I know you use snap too because I found this GitHUB repository just on a snap forum topic that has a heading"Python#"



---Original---

**Pull request closed without merging**
